Repository KAU2024-SANHAK/SANHAK_Client, pull requests merged in 2024-05, with the labels that each got.

#59 [feat] fastDiary에서 keyword가 null값인지 체크하여 모달창을 띄우기
  src/components/FastDiarySteps/FastDiaryStep6/FastDiaryStep6.jsx
  src/hooks/useKeywordNullCheck.jsx
  src/recoil/atoms.js
Labels: feat, 일기작성

#62 [refactor] kakao login 로직 수정
  src/apis/client.js
  src/components/Login.jsx
  src/hooks/auth/useLogin.jsx
  src/hooks/queries/member/members/useLogin.jsx
  src/pages/Start/Start.jsx
  src/router/Router.jsx
Labels: refactor

#72 [feat] diaryType 설정 api 연결
  src/components/OnBoardingSteps/OnBoardingStep5/OnBoardingStep5.jsx
  src/components/SetDiaryStyle/SetDiaryStyle.jsx
  src/hooks/diary/useHandelDiaryType.jsx
  src/hooks/queries/onboarding/usePostDiaryType.jsx
  src/pages/MyPage/MyPagePopUp/MyPagePopUp.jsx
  src/recoil/atoms.js
Labels: feat, 온보딩, 마이페이지

#69 [feat] 카카오 로그아웃 구현
  src/components/OnBoardingSteps/OnBoardingStep5/OnBoardingStep5.jsx
  src/hooks/queries/member/members/useLogout.jsx
  src/hooks/queries/onboarding/usePostDiaryType.jsx
  src/pages/MyPage/MyPagePopUp/MyPagePopUp.jsx
  src/pages/Start/Start.jsx
Labels: feat, 로그인

#74 [feat] 감정별 일기 조회 api 연결
  src/components/FastDiarySteps/FastDiaryStep6/FastDiaryStep6.jsx
  src/components/Modal/DiaryErrorModal.jsx
  src/components/Modal/EmptyDiaryFeelingModal.jsx
  src/components/common/buttons/EmotionType/EmotionType.jsx
  src/hooks/queries/mypage/usePostFeelingList.jsx
  src/pages/DiaryList/DiaryList.jsx
  src/pages/SearchByEmotion/SearchByEmotion.jsx
  src/pages/SearchByEmotion/SearchByEmotionPopUp/SearchByEmotionPopUp.jsx
  src/recoil/atoms.js
Labels: feat, 감정별 조회

#49 Feat/#46/create diary publishing
  src/assets/svg/IcAngry.jsx
  src/assets/svg/IcGoToReplyBtn.jsx
  src/assets/svg/IcHappy.jsx
  src/assets/svg/IcRelax.jsx
  src/assets/svg/IcSad.jsx
  src/assets/svg/IcSurprised.jsx
  src/assets/svg/IcTodayEmotionBtn.jsx
  src/assets/svg/IcWorried.jsx
  src/assets/svg/IcXBtn.jsx
  src/assets/svg/index.js
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/CreatedDiary/CreatedDiary.style.js
  src/components/EmotionViewComponent/EmotionViewComponent.jsx
  src/components/EmotionViewComponent/EmotionViewComponent.style.js
  src/components/PopUp/PopUp.style.js
  src/components/common/DiaryListComponent/DiaryListComponent.jsx
  src/components/common/buttons/Back/BtnBack.jsx
  src/components/common/buttons/GoToEmotionViewBtn/RequestEmotionViewBtn/RequestEmotionViewBtn.jsx
  src/components/common/buttons/GoToEmotionViewBtn/RequestEmotionViewBtn/RequestEmotionViewBtn.style.js
  src/components/common/buttons/GoToEmotionViewBtn/ResponseEmotionViewBtn/ResponseEmotionViewBtn.jsx
  src/components/common/buttons/GoToEmotionViewBtn/ResponseEmotionViewBtn/ResponseEmotionViewBtn.style.js
  src/components/common/buttons/GoToReplyViewBtn/RequestReplyViewBtn/RequestReplyViewBtn.jsx
  src/components/common/buttons/GoToReplyViewBtn/RequestReplyViewBtn/RequestReplyViewBtn.style.js
  src/components/common/buttons/GoToReplyViewBtn/ResponseReplyViewBtn/ResponseReplyViewBtn.jsx
  src/components/common/buttons/GoToReplyViewBtn/ResponseReplyViewBtn/ResponseReplyViewBtn.style.js
  src/hooks/queries/create/usePostAdvice.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/DiaryView/DiaryView.style.js
  src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.jsx
  src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.style.js
  src/pages/EmotionView/EmotionView.jsx
  src/pages/EmotionView/EmotionView.style.js
  src/recoil/atoms.js
  src/router/Router.jsx
  src/utils/diaryContent.js
Labels: feat

#81 [feat] 느린 일기와 빠른 일기 api를 연결합니다
  package.json
  src/apis/client.js
  src/assets/InputCloud.png
  src/assets/InputCloud.svg
  src/assets/largeQuestionBox.svg
  src/assets/largeSpeakCloud.png
  src/assets/smallQuestionBox.svg
  src/assets/smallSpeakCloud.png
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/FastDiarySteps/FastDiaryStep1/FastDiaryStep1.jsx
  src/components/FastDiarySteps/FastDiaryStep2/FastDiaryStep2.jsx
  src/components/FastDiarySteps/FastDiaryStep3/FastDiaryStep3.jsx
  src/components/FastDiarySteps/FastDiaryStep4/FastDiaryStep4.jsx
  src/components/FastDiarySteps/FastDiaryStep5/FastDiaryStep5.jsx
  src/components/FastDiarySteps/FastDiaryStep6/FastDiaryStep6.jsx
  src/components/FastDiarySteps/Questions/LargeQustion.jsx
  src/components/FastDiarySteps/Questions/Question.style.js
  src/components/FastDiarySteps/Questions/SamllQuestion.jsx
  src/components/common/buttons/KakaoLogin/BtnTestLogin.jsx
  src/hooks/common/useSetDiaryAtoms.jsx
  src/hooks/queries/fastdiary/usePostKeywords.jsx
  src/hooks/queries/member/members/usePostLoginToken.jsx
  src/hooks/queries/slowdiary/usePostSlowDiary.jsx
  src/hooks/useTestLogin.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/SlowDiary/SlowDiary.jsx
  src/recoil/atoms.js
  src/setupProxy.js
  src/utils/keyword.js
  vite.config.js
  yarn.lock
Labels: feat, 일기작성

#85 [feat] 감정 분석 제외 ai서버 api 연결
  src/assets/svg/IcAngryHoneyBear.jsx
  src/assets/svg/IcHappyHoneyBear.jsx
  src/assets/svg/IcNoneHoeyBear.jsx
  src/assets/svg/IcRelaxHoneyBear.jsx
  src/assets/svg/IcSadHoneyBear.jsx
  src/assets/svg/IcWorriedHoneyBear.jsx
  src/assets/svg/index.js
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/CreatedDiary/CreatedDiary.style.js
  src/components/EmotionViewComponent/EmotionViewComponent.jsx
  src/components/EmotionViewComponent/EmotionViewComponent.style.js
  src/components/FastDiarySteps/FastDiaryStep6.jsx
  src/components/Modal/DiaryErrorModal.jsx
  src/components/Modal/HomeModal.jsx
  src/components/common/Calendar/Calendar.jsx
  src/components/common/DiaryListComponent/DiaryListComponent.jsx
  src/components/common/HoneyBear/FeelingHoneyBear.jsx
  src/components/common/HoneyBear/FeelingHoneyBear.style.js
  src/components/common/buttons/Back/BtnBack.jsx
  src/components/common/buttons/Back/BtnBack.style.js
  src/components/common/buttons/ShowAdvice/BtnShowAdvice.jsx
  src/components/common/buttons/ShowAdvice/BtnShowAdvice.style.js
  src/components/common/buttons/ShowFeeling/BtnShowFeeling.jsx
  src/components/common/buttons/ShowFeeling/BtnShowFeeling.style.js
  src/components/common/buttons/Submit/BtnSubmit.jsx
  src/components/common/buttons/Submit/BtnSubmit.style.js
  src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.jsx
  src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.style.js
  src/components/common/buttons/WriteDiaryButton/WriteDiaryButton.jsx
  src/components/common/buttons/WriteDiaryButton/WriteDiaryButton.style.js
  src/hooks/diary/useResetDiaryAtom.jsx
  src/hooks/diary/useResetKeywords.jsx
  src/hooks/queries/create/usePostAdvice.jsx
  src/hooks/queries/create/usePostFeeling.jsx
  src/hooks/queries/etc/usePostDiary.jsx
  src/hooks/queries/member/members/useLogout.jsx
  src/hooks/queries/slowdiary/usePostSlowDiary.jsx
  src/pages/CharacterWiki/CharacterWiki.jsx
  src/pages/DiaryList/DiaryList.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/EmotionView/EmotionView.jsx
  src/pages/Loading/Loading.style.js
  src/pages/Main/Main.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPagePopUp/MyPagePopUp.jsx
  src/pages/SearchByEmotion/SearchByEmotion.jsx
  src/pages/SearchByEmotion/SearchByEmotionPopUp/SearchByEmotionPopUp.jsx
  src/pages/SlowDiary/SlowDiary.jsx
  src/pages/SummaryTest/SummaryTest.jsx
  src/pages/SummaryTest/SummaryTest.style.js
  src/router/Router.jsx
  src/setupProxy.js
  src/utils/convertFeelingText.js
  src/utils/diaryContent.js
  src/utils/onDiary.js
Labels: feat, 일기작성

#95 [refactor] 중간 발표 전 최종 리팩토링
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/FastDiarySteps/FastDiaryStep6.jsx
  src/components/common/HoneyBear/FeelingHoneyBear.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.style.js
  src/pages/EmotionView/EmotionView.jsx
  src/utils/convertFeelingText.js
Labels: refactor

#96 Develop에서 Main merge (중간 발표 최종 리팩토링)
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/FastDiarySteps/FastDiaryStep6.jsx
  src/components/common/HoneyBear/FeelingHoneyBear.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.style.js
  src/pages/EmotionView/EmotionView.jsx
  src/utils/convertFeelingText.js
Labels: merge

#103 [리팩토링] 개발자 모드 없는 화면에서 스타일 깨지지 않도록 수정 및 첫 로그인 후 온보딩에서 api 되도록 수정
  src/assets/img/InputCloud.svg
  src/assets/img/largeQuestionBox.svg
  src/assets/img/smallQuestionBox.svg
  src/assets/svg/IcHoneyBear.jsx
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/OnBoardingSteps/OnBoardingStep.style.js
  src/components/OnBoardingSteps/OnBoardingStep1.jsx
  src/components/OnBoardingSteps/OnBoardingStep5.jsx
  src/components/PopUp/PopUp.style.js
  src/components/common/HoneyBear/FeelingHoneyBear.jsx
  src/hooks/diary/useResetKeywords.jsx
  src/hooks/queries/onboarding/usePostDiaryType.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.js
  src/pages/OnBoarding/OnBoarding.jsx
  src/pages/SearchByEmotion/SearchByEmotion.style.js
  src/pages/SearchByEmotion/SearchByEmotionPopUp/SearchByEmotionPopUp.style.js
  src/pages/SlowDiary/SlowDiary.jsx
  src/pages/WriteDiary/WriteDiary.jsx
  src/pages/WriteDiary/WriteDiary.style.js
  src/utils/convertFeelingText.js
Labels: refactor

#106 [feat] 카카오 공유하기
  index.html
  src/pages/DiaryView/DiaryView.jsx
  src/utils/shareKakao.js
Labels: feat

#109 [feat] 광고 시스템 삽입
  src/components/KakaoAd/KakaoAd.jsx
  src/components/KakaoAd/KakaoAd.style.js
  src/components/KakaoAd/KakaoAdCallback.jsx
  src/components/MainStep/MainStep1/MainStep1.jsx
Labels: feat

#113 [feat] AI 이미지 생성 api 연결
  src/assets/lottie/circleLottie.json
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/Loading/AdviceLoading/AdviceLoading.jsx
  src/components/Loading/CircleLoading/CircleLoading.jsx
  src/components/Loading/CircleLoading/CircleLoading.style.js
  src/hooks/queries/create/usePostAiImage.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/SearchByEmotion/SearchByEmotion.jsx
  src/pages/SlowDiary/SlowDiary.jsx
Labels: feat, 일기작성

#118 [feat] 일기 삭제시 모달창 띄우기
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/CreatedDiary/CreatedDiary.style.js
  src/components/Modal/Modal.style.js
  src/components/Modal/OptionModal.jsx
  src/components/common/buttons/Menu/Menu.jsx
  src/components/common/buttons/Menu/Menu.style.js
  src/components/common/buttons/Share/Share.jsx
  src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.style.js
  src/pages/DiaryView/DiaryView.jsx
  src/pages/DiaryView/DiaryView.style.js
  src/pages/FastDiary/FastDiary.jsx
  src/pages/MyPage/MyPage.style.js
  src/pages/SearchByEmotion/SearchByEmotion.style.js
  src/pages/SlowDiary/SlowDiary.jsx
Labels: feat, 일기작성

#126 [refactor] 배포페이지에서 absolute를 활용해 깨지는 부분에 대해서 수정
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/MainStep/MainStep1/MainStep1.style.js
  src/components/MainStep/MainStep2/MainStep2.style.js
  src/components/common/buttons/MyPageButton/MyPageButton.jsx
  src/components/common/buttons/MyPageButton/MyPageButton.style.js
  src/components/common/buttons/SearchByEmotionButton/SearchByEmotionButton.jsx
  src/components/common/buttons/SearchByEmotionButton/SearchByEmotionButton.style.js
  src/pages/FastDiary/FastDiary.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.js
Labels: refactor

#131 [refactor] 조언 오타 수정 및 로딩창 width 조정
  src/pages/DiaryView/DiaryView.jsx
  src/pages/Loading/Loading.jsx
  src/pages/Loading/Loading.style.js
Labels: refactor

#135 [feat] 백 서버와 ai이미지 생성 연결
  src/hooks/queries/create/usePostAiImage.jsx
Labels: feat, 일기작성

#143 [style] 자잘한 css 수정 사항들 1차 qa
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/FastDiarySteps/FastDiaryStep2.jsx
  src/components/FastDiarySteps/FastDiaryStep3.jsx
  src/components/FastDiarySteps/FastDiaryStep4.jsx
  src/components/FastDiarySteps/FastDiaryStep5.jsx
  src/components/FastDiarySteps/FastDiaryStep6.jsx
  src/components/FastDiarySteps/FeelingHive/FeelingHive.jsx
  src/components/FastDiarySteps/FeelingHive/FeelingHive.style.js
  src/components/FastDiarySteps/Questions/LargeQustion.jsx
  src/components/FastDiarySteps/Questions/Question.style.js
  src/components/FastDiarySteps/Questions/SamllQuestion.jsx
  src/components/OnBoardingSteps/OnBoardingStep.style.js
  src/components/OnBoardingSteps/OnBoardingStep1.jsx
  src/components/common/buttons/MyPageButton/MyPageButton.style.js
  src/components/common/buttons/SearchByEmotionButton/SearchByEmotionButton.style.js
  src/pages/FastDiary/FastDiary.style.js
  src/pages/OnBoarding/OnBoarding.jsx
  src/pages/OnBoarding/OnBoarding.style.js
  src/pages/Start/Start.jsx
  src/pages/Start/Start.style.js
Labels: refactor, style

#148 [feat]유튜브 플레이리스트 api 연결
  src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.jsx
  src/hooks/queries/create/usePostAdvice.jsx
  src/hooks/queries/main/usePostPlaylist.jsx
Labels: feat, 마이페이지

#150 [feat] 감정 생성 불가 에러 모달 및 따옴표 파싱
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/CreatedDiary/CreatedDiary.style.js
  src/components/MainStep/MainStep2/MainStep2.jsx
  src/components/common/DiaryListComponent/DiaryListComponent.jsx
  src/pages/DiaryList/DiaryList.jsx
  src/pages/SearchByEmotion/SearchByEmotionPopUp/SearchByEmotionPopUp.jsx
Labels: feat

#153 [feat]카카오 공유하기 구현
  src/apis/client.js
  src/components/common/buttons/Share/Share.jsx
  src/hooks/queries/etc/useGetSharedDiary.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/SharedView/SharedView.jsx
  src/pages/SharedView/SharedView.style.js
  src/recoil/atoms.js
  src/router/Router.jsx
  src/utils/shareKakao.js
Labels: feat, refactor

#152 [style] start, onboarding, fast diary, main 스타일 수정
  src/components/MainStep/MainStep1/MainStep1.jsx
  src/components/MainStep/MainStep1/MainStep1.style.js
  src/components/OnBoardingSteps/OnBoardingStep.style.js
  src/components/OnBoardingSteps/title/Title.style.js
  src/components/common/HoneyBear/HoneyBear.jsx
  src/hooks/useMobile.jsx
  src/pages/FastDiary/FastDiary.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.js
  src/pages/Start/Start.jsx
Labels: refactor, style
