Repository KAU2024-SANHAK/SANHAK_Client, pull requests merged in 2024-04, with the labels that each got.

#26 Feat/#25 start after login
  src/assets/svg/IcStartButton.jsx
  src/components/common/buttons/KakaoLogin/BtnKakaoLogin.jsx
  src/components/common/buttons/KakaoLogin/BtnKakoLogin.style.js
  src/components/common/buttons/Start/BtnStart.jsx
  src/components/common/buttons/Start/BtnStart.style.js
  src/hooks/queries/member/members/useLogin.jsx
  src/pages/Main/Main.jsx
  src/pages/Start/Start.jsx
  src/router/Router.jsx
Labels: feat

#27 Feat/#23 onboarding
  src/assets/svg/IcBlank.jsx
  src/assets/svg/IcCurrentProgressCircle.jsx
  src/assets/svg/IcProgressCircle.jsx
  src/components/OnBoardingProgressBar/OnBoardingPrgoressBar.jsx
  src/components/OnBoardingProgressBar/OnBoardingProgressBar.style.js
  src/components/OnBoardingSteps/SetWriitingStyle/SetWritingStyle.jsx
  src/components/OnBoardingSteps/SetWriitingStyle/SetWritingStyle.style.js
  src/components/OnBoardingSteps/Step.style.js
  src/components/OnBoardingSteps/Step1/Step1.jsx
  src/components/OnBoardingSteps/Step2/Step2.jsx
  src/components/OnBoardingSteps/Step3/Step3.jsx
  src/components/OnBoardingSteps/Step4/Step4.jsx
  src/components/OnBoardingSteps/Step5/Step5.jsx
  src/components/OnBoardingSteps/Step6/Step6.jsx
  src/components/OnBoardingSteps/title/SubTitle.jsx
  src/components/OnBoardingSteps/title/Title.jsx
  src/components/OnBoardingSteps/title/Title.style.js
  src/components/common/.gitkeep
  src/components/common/buttons/OnBoardingNext/BtnOnBoardingNext.jsx
  src/components/common/buttons/OnBoardingNext/BtnOnBoardingNext.style.js
  src/components/common/buttons/Start/BtnStart.jsx
  src/hooks/common/useFunnel.jsx
  src/hooks/queries/member/members/useLogin.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.js
  src/pages/OnBoarding/OnBoarding.jsx
  src/pages/OnBoarding/OnBoarding.style.js
  src/router/Router.jsx
  src/styles/GlobalStyle.js
Labels: 온보딩

#37 [feat] pretendard 적용 및, theme 파일 수정
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-Thin.woff
  src/assets/fonts/pretendard.css
  src/pages/Start/Start.style.js
  src/styles/theme.js
Labels: feat

#32 Feat/#31 onboarding style
  src/assets/onBoardingStep1.png
  src/assets/onBoardingStep2.png
  src/assets/onBoardingStep3.png
  src/assets/onBoardingStep4.png
  src/assets/svg/IcBlank.jsx
  src/assets/svg/IcCurrentProgressCircle.jsx
  src/assets/svg/IcHoneyBear.jsx
  src/assets/svg/IcKakaoLogin.jsx
  src/assets/svg/IcNextButton.jsx
  src/assets/svg/IcProgressCircle.jsx
  src/assets/svg/IcStartButton.jsx
  src/assets/svg/index.js
  src/components/OnBoardingProgressBar/OnBoardingProgressBar.style.js
  src/components/OnBoardingSteps/SetWriitingStyle/SetWritingStyle.jsx
  src/components/OnBoardingSteps/SetWriitingStyle/SetWritingStyle.style.js
  src/components/OnBoardingSteps/Step.style.js
  src/components/OnBoardingSteps/Step1/Step1.jsx
  src/components/OnBoardingSteps/Step2/Step2.jsx
  src/components/OnBoardingSteps/Step3/Step3.jsx
  src/components/OnBoardingSteps/Step4/Step4.jsx
  src/components/OnBoardingSteps/Step5/Step5.jsx
  src/components/OnBoardingSteps/Step6/Step6.jsx
  src/components/OnBoardingSteps/title/Caption.jsx
  src/components/OnBoardingSteps/title/SubTitle.jsx
  src/components/OnBoardingSteps/title/Title.jsx
  src/components/OnBoardingSteps/title/Title.style.js
  src/components/common/HoneyBear/HoneyBear.jsx
  src/components/common/HoneyBear/HoneyBear.style.js
  src/components/common/buttons/OnBoardingNext/BtnOnBoardingNext.jsx
  src/components/common/buttons/OnBoardingNext/BtnOnBoardingNext.style.js
  src/components/common/buttons/complete/BtnComplete.jsx
  src/components/common/buttons/complete/BtnComplete.style.js
  src/components/common/buttons/setDiaryType/BtnSetDiaryType.jsx
  src/components/common/buttons/setDiaryType/BtnSetDiaryType.style.js
  src/pages/OnBoarding/OnBoarding.style.js
Labels: feat

#34 Feat/#28 fast diary page
  src/assets/svg/IcDiaryProgress1.jsx
  src/assets/svg/IcDiaryProgress2.jsx
  src/assets/svg/IcDiaryProgress3.jsx
  src/assets/svg/IcDiaryProgress4.jsx
  src/assets/svg/IcDiaryProgress5.jsx
  src/assets/svg/IcDiaryProgress6.jsx
  src/assets/svg/IcHome.jsx
  src/assets/svg/index.js
  src/components/DiaryProgress/DiaryProgress.jsx
  src/components/DiaryProgress/DiaryProgress.style.js
  src/components/Modal/HomeModal.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.js
  src/components/OnBoardingProgressBar/OnBoardingPrgoressBar.jsx
  src/components/OnBoardingProgressBar/OnBoardingProgressBar.style.js
  src/components/OnBoardingSteps/Step1/Step1.jsx
  src/components/OnBoardingSteps/Step2/Step2.jsx
  src/components/OnBoardingSteps/Step3/Step3.jsx
  src/components/OnBoardingSteps/Step4/Step4.jsx
  src/components/OnBoardingSteps/Step5/Step5.jsx
  src/components/OnBoardingSteps/Step6/Step6.jsx
  src/components/common/HoneyBear/HoneyBear.style.js
  src/components/common/StepPrgoress/StepProgress.jsx
  src/components/common/StepPrgoress/StepProgress.style.js
  src/components/common/buttons/Home/BtnHome.jsx
  src/components/common/buttons/Home/BtnHome.style.js
  src/components/common/buttons/OnBoardingNext/BtnOnBoardingNext.style.js
  src/components/common/buttons/Start/BtnStart.jsx
  src/components/common/buttons/Start/BtnStart.style.js
  src/components/common/buttons/Submit/BtnSubmit.jsx
  src/components/common/buttons/Submit/BtnSubmit.style.js
  src/hooks/common/useModal.jsx
  src/pages/FastDiary/FastDiary.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/OnBoarding/OnBoarding.jsx
  src/pages/OnBoarding/OnBoarding.style.js
  src/router/Router.jsx
  src/styles/theme.js
Labels: feat

#35 Feat/#30 slow diary
  src/assets/svg/IcAddImage.jsx
  src/assets/svg/index.js
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/common/buttons/Home/BtnHome.jsx
  src/components/common/buttons/Home/BtnHome.style.js
  src/components/common/buttons/Next/BtnNext.style.js
  src/components/common/buttons/Prev/BtnPrev.style.js
  src/pages/FastDiary/FastDiary.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/SlowDiary/SlowDiary.jsx
  src/pages/SlowDiary/SlowDiary.style.js
  src/router/Router.jsx
Labels: feat

#43 [feat] 마이페이지 뷰 구현
  src/assets/svg/IcBackButton.jsx
  src/assets/svg/IcPopUpSlide.jsx
  src/assets/svg/index.js
  src/components/Modal/SetWritingStyleModal/SetWritingStyleModal.jsx
  src/components/Modal/SetWritingStyleModal/SetWritingStyleModal.style.js
  src/components/PopUp/MyPagePopUp/MyPagePopUp.jsx
  src/components/PopUp/MyPagePopUp/MyPagePopUp.style.js
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.style.js
  src/components/common/buttons/Back/BtnBack.jsx
  src/components/common/buttons/Back/BtnBack.style.js
  src/components/common/buttons/Logout/BtnLogout.jsx
  src/components/common/buttons/Logout/BtnLogout.style.js
  src/components/common/buttons/SetCharcater/BtnSetCharacter.jsx
  src/components/common/buttons/SetCharcater/BtnSetCharacter.style.js
  src/components/common/buttons/SetDiaryModal/BtnSetDiaryModal.jsx
  src/components/common/buttons/SetDiaryModal/BtnSetDiaryModal.style.js
  src/components/common/buttons/complete/BtnComplete.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.js
  src/router/Router.jsx
Labels: feat

#44 Develop에서 main merge (마이페이지 뷰 반영)
  src/assets/svg/IcBackButton.jsx
  src/assets/svg/IcPopUpSlide.jsx
  src/assets/svg/index.js
  src/components/Modal/SetWritingStyleModal/SetWritingStyleModal.jsx
  src/components/Modal/SetWritingStyleModal/SetWritingStyleModal.style.js
  src/components/PopUp/MyPagePopUp/MyPagePopUp.jsx
  src/components/PopUp/MyPagePopUp/MyPagePopUp.style.js
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.style.js
  src/components/common/buttons/Back/BtnBack.jsx
  src/components/common/buttons/Back/BtnBack.style.js
  src/components/common/buttons/Logout/BtnLogout.jsx
  src/components/common/buttons/Logout/BtnLogout.style.js
  src/components/common/buttons/SetCharcater/BtnSetCharacter.jsx
  src/components/common/buttons/SetCharcater/BtnSetCharacter.style.js
  src/components/common/buttons/SetDiaryModal/BtnSetDiaryModal.jsx
  src/components/common/buttons/SetDiaryModal/BtnSetDiaryModal.style.js
  src/components/common/buttons/complete/BtnComplete.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.js
  src/router/Router.jsx
Labels: merge

#47 [feat] 캐릭터 도감 페이지 구현 및 마이페이지 수정
  package.json
  src/components/Carousel/WikiCarousel/CharacterBox.jsx
  src/components/Carousel/WikiCarousel/WikiCarousel.jsx
  src/components/Carousel/WikiCarousel/WikiCarousel.style.js
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/FastDiarySteps/FastDiaryStep1/FastDiaryStep1.jsx
  src/components/Modal/SetWritingStyleModal/SetWritingStyleModal.jsx
  src/components/Modal/SetWritingStyleModal/SetWritingStyleModal.style.js
  src/components/OnBoardingSteps/SetWriitingStyle/SetWritingStyle.jsx
  src/components/OnBoardingSteps/Step.style.js
  src/components/OnBoardingSteps/Step5/Step5.jsx
  src/components/PopUp/MyPagePopUp/MyPagePopUp.jsx
  src/components/PopUp/PopUp.jsx
  src/components/SetDiaryStyle/SetDiaryStyle.jsx
  src/components/SetDiaryStyle/SetDiaryStyle.style.js
  src/components/common/buttons/Back/BtnBack.jsx
  src/components/common/buttons/CurDiaryType/BtnCurDiaryType.jsx
  src/components/common/buttons/CurDiaryType/BtnCurDiaryType.style.js
  src/components/common/buttons/Logout/BtnLogout.jsx
  src/components/common/buttons/Logout/BtnLogout.style.js
  src/components/common/buttons/SetCharcater/BtnSetCharacter.jsx
  src/components/common/buttons/SetDiaryModal/BtnSetDiaryModal.jsx
  src/hooks/queries/member/members/useLogout.jsx
  src/pages/CharacterWiki/CharacterWiki.jsx
  src/pages/CharacterWiki/CharacterWiki.style.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPagePopUp/MyPagePopUp.jsx
  src/pages/MyPage/MyPagePopUp/MyPagePopUp.style.js
  src/recoil/atoms.js
  src/router/Router.jsx
  yarn.lock
Labels: feat, 마이페이지

#55 [feat] favicon 추가 및 사진 넣기 및 ogtag 설정
  index.html
  public/apple-touch-icon.png
  public/favicon.ico
  public/ogtag_image.png
Labels: feat

#52 [feat] instance 설정 및 react-query hooks 생성
  src/apis/client.js
  src/components/Login.jsx
  src/hooks/auth/useLogin.jsx
  src/hooks/queries/create/usePostAdvice.jsx
  src/hooks/queries/create/usePostFeeling.jsx
  src/hooks/queries/etc/usePostDiary.jsx
  src/hooks/queries/fastdiary/usePostKeywords.jsx
  src/hooks/queries/main/useGetSummary.jsx
  src/hooks/queries/main/usePostCalendar.jsx
  src/hooks/queries/member/members/useLogin.jsx
  src/hooks/queries/mypage/usePostFeelingList.jsx
  src/hooks/queries/onboarding/usePostDiaryType.jsx
  src/hooks/queries/slowdiary/usePostSlowDiary.jsx
  src/pages/Start/Start.jsx
Labels: feat

#57 Develop에서 main merge
  index.html
Labels: merge, fix
