Repository KAU2024-SANHAK/SANHAK_Client, pull requests merged in 2024-06, with the labels that each got.

#168 [refactor] 마이페이지, 감정별 조회 페이지, 느린 일기, 빠른 일기 페이지 스타일 수정
  src/components/DiaryProgress/DiaryProgress.style.js
  src/components/FastDiarySteps/FastDiaryStep.style.js
  src/components/FastDiarySteps/FastDiaryStep1.jsx
  src/components/FastDiarySteps/FeelingHive/FeelingHive.style.js
  src/components/FastDiarySteps/Questions/LargeQustion.jsx
  src/components/FastDiarySteps/Questions/Question.style.js
  src/components/FastDiarySteps/Questions/SamllQuestion.jsx
  src/components/common/buttons/Home/BtnHome.style.js
  src/components/common/buttons/Prev/BtnPrev.style.js
  src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.style.js
  src/pages/DiaryList/DiaryList.sytle.js
  src/pages/DiaryView/DiaryView.jsx
  src/pages/DiaryView/DiaryView.style.js
  src/pages/FastDiary/FastDiary.jsx
  src/pages/FastDiary/FastDiary.style.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.js
  src/pages/SearchByEmotion/SearchByEmotion.jsx
  src/pages/SearchByEmotion/SearchByEmotion.style.js
  src/pages/SlowDiary/SlowDiary.jsx
  src/pages/SlowDiary/SlowDiary.style.js
  src/recoil/atoms.js
Labels: 일기작성, 메인페이지, 마이페이지, refactor, 감정별 조회, style

#174 [feat] mypage character
  src/assets/svg/IcBearHoneyBee.jsx
  src/assets/svg/IcBeeHoneyBear.jsx
  src/assets/svg/IcHoneyBee.jsx
  src/assets/svg/IcPrinceHoneyBear.jsx
  src/assets/svg/IcPrinceHoneyBee.jsx
  src/assets/svg/IcRichHoneyBear.jsx
  src/assets/svg/IcRichHoneyBee.jsx
  src/assets/svg/IcStudentHoneyBear.jsx
  src/assets/svg/IcStudentHoneyBee.jsx
  src/assets/svg/index.js
  src/components/Carousel/WikiCarousel/CharacterBox.jsx
  src/components/Carousel/WikiCarousel/WikiCarousel.style.js
  src/pages/CharacterWiki/CharacterWiki.jsx
  src/pages/CharacterWiki/CharacterWiki.style.js
Labels: feat

#172 [refactor] 로딩 컴포넌트 텍스트 추가
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/Loading/CircleLoading/CircleLoading.style.js
  src/pages/CharacterWiki/CharacterWiki.style.js
  src/pages/DiaryView/DiaryView.jsx
  src/pages/Loading/Loading.jsx
  src/pages/Loading/Loading.style.js
Labels: refactor, style

#176 [feat] 날씨 API 연결 후 렌더링
  src/components/MainStep/MainStep1/MainStep1.jsx
  src/components/MainStep/MainStep1/MainStep1.style.js
  src/components/MainStep/MainStep1/WeatherPlaylist/WeatherPlaylist.jsx
  src/components/MainStep/MainStep1/WeatherPlaylist/WeatherPlaylist.style.js
  src/components/common/buttons/SearchByEmotionButton/SearchByEmotionButton.jsx
  src/hooks/queries/main/useGetWeather.jsx
  src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.jsx
Labels: feat, 메인페이지

#187 [refactor] 로딩 컴포넌트 position 값 및 텍스트 수정
  src/components/CreatedDiary/CreatedDiary.jsx
  src/pages/DiaryView/DiaryView.jsx
  src/pages/Loading/Loading.style.js
Labels: refactor

#191 [refactor] 온보딜 step5 컴포넌트 및 캡션 width값, margin값 수정
  src/components/OnBoardingSteps/OnBoardingStep.style.js
  src/components/OnBoardingSteps/OnBoardingStep5.jsx
  src/components/OnBoardingSteps/title/Caption.jsx
  src/components/OnBoardingSteps/title/Title.style.js
Labels: refactor, style

#190 Develop에서 main merge (최종발표 전 스타일 수정)
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/OnBoardingSteps/OnBoardingStep.style.js
  src/components/OnBoardingSteps/OnBoardingStep5.jsx
  src/components/OnBoardingSteps/title/Caption.jsx
  src/components/OnBoardingSteps/title/Title.style.js
  src/components/common/buttons/Menu/Menu.style.js
  src/components/common/buttons/ShowAdvice/BtnShowAdvice.style.js
  src/components/common/buttons/ShowFeeling/BtnShowFeeling.style.js
  src/pages/DiaryView/DiaryView.jsx
  src/pages/Loading/Loading.style.js
  src/pages/SharedView/SharedView.jsx
  src/pages/SharedView/SharedView.style.js
Labels: merge

#195 Refactor/#193 create feeling none
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/FastDiarySteps/FastDiaryStep6.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.js
  src/hooks/useKeywordNullCheck.jsx
Labels: refactor

#212 [refactor]날씨 주석 해제
  src/components/CreatedDiary/CreatedDiary.jsx
  src/components/MainStep/MainStep1/MainStep1.jsx
  src/components/MainStep/MainStep1/WeatherPlaylist/WeatherPlaylist.jsx
Labels: refactor
